import mongoose from "mongoose";

const ContactSchema = new mongoose.Schema({
    additionalInfo: { type: mongoose.Schema.Types.Mixed, default: {} },
    additionalOpeningHours: { type: mongoose.Schema.Types.Mixed, default: {} },
    address: { type: String },
    categories: [String],
    categoryName: String,
    cid: String,
    city: String,
    claimThisBusiness: Boolean,
    countryCode: String,
    domain: String,
    emails: [String],
    facebooks: [String],
    fid: String,
    googleFoodUrl: String,
    imageUrl: String,
    imagesCount: Number,
    instagrams: [String],
    isAdvertisement: Boolean,
    kgmid: String,
    language: String,
    linkedIns: [String],
    location: {
      lat: Number,
      lng: Number,
    },
    neighborhood: String,
    openingHours: [
      {
        day: String,
        hours: String,
      },
    ],
    permanentlyClosed: Boolean,
    phone: String,
    phoneUnformatted: String,
    phones: [String],
    phonesUncertain: [String],
    placeId: String,
    postalCode: String,
    price: String,
    rank: Number,
    reviewsCount: Number,
    scrapedAt: Date,
    searchPageUrl: String,
    searchString: String,
    state: String,
    street: String,
    temporarilyClosed: Boolean,
    tiktoks: [String],
    title: String,
    totalScore: Number,
    twitters: [String],
    url: String,
    website: String,
    youtubes: [String],

    hasContacted: { type: Boolean, default: false },
    hasContactedDate: String,
    typesContact: [String],
  },
  { timestamps: true }
)

export const ContactModel = mongoose.model("Contact", ContactSchema);